modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="All rights reserved"
[[mods]] #mandatory
# The modid of the mod
modId="atmos" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Atmos Client" #mandatory
displayURL="https://www.egghof.it" #optional
logoFile="examplemod.png" #optional 
credits="Thanks for this example mod goes to Java" #optional
authors="CrazyPhil"
description='''
Hmm
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.atmos]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[39,)" #mandatory
    ordering="NONE"
    # Side this dependency is applied on - BOTH, CLIENT or SERVER
    side="BOTH"
# Here's another dependency
[[dependencies.atmos]]
    modId="minecraft"
    mandatory=true
# This version range declares a minimum of the current minecraft version up to but not including the next major version
    versionRange="[1.18.1,1.19)"
    ordering="NONE"
    side="BOTH"
